### ISSUE TITLE
Non-English Clients cannot use Ocean Trip

### ISSUE THREAD

**Issue by catrenelle** [catrenelle/OceanTrip#39]
Because of how Ocean Trip works to determine the zone, it's unable to work on Non English clients. The game doesn't give you any indication as to which of the 3 routes you are on when you are on The Endeavour.

To get around this and remove this limitation, the following should take place:
* When starting from the beginning, we already know the route we're taking.  Maintain a counter that goes from 1-3 if stopped/restarted within the same route.
* If RB has been restarted or wasn't enabled until the user is already on the boat, catching one fish will instantly tell you the route you are on. 

What we cannot programmatically determine in advance (as far as I am aware):
* Time of Day
* Route ("The Endeavour" is a default static value, there is no subzone to go on)
* Weather

Algorithms can tell us the route and time of day, but nothing can  tell the weather until you're on the boat.

**Comment by ripsnortntear** [comment]
There’s a website that list at least three days of voyages and what they’re gonna be all that information is already knowNSent from my iPhoneOn Jun 24, 2023, at 5:06 PM, Catherine Renelle ***@***.***> wrote:﻿
Because of how Ocean Trip works to determine the zone, it's unable to work on Non English clients. The game doesn't give you any indication as to which of the 3 routes you are on when you are on The Endeavour.
To get around this and remove this limitation, the following should take place:

When starting from the beginning, we already know the route we're taking.  Maintain a counter that goes from 1-3 if stopped/restarted within the same route.
If RB has been restarted or wasn't enabled until the user is already on the boat, catching one fish will instantly tell you the route you are on.

What we cannot programmatically determine in advance (as far as I am aware):

Time of Day
Route ("The Endeavour" is a default static value, there is no subzone to go on)
Weather

Algorithms can tell us the route and time of day, but nothing can  tell the weather until you're on the boat.

**Comment by catrenelle** [comment]
We can pre-calculate every route until the end of time. The issue stems from mid-voyage.

Let's say you're on the Ruby route in Kugane (2nd of the 3 trips). If you start the Botbase fresh at this point, it won't know you're in Kugane and think you're in the Sirensong Sea. This is because there is nothing in memory that I am aware of that tells you exactly where you are in the boat trips.

**Comment by catrenelle** [comment]
An update will be pushed soon that should allow this to work with Non en-us users, including the CN client. The UI will still mostly be in English except for item names that are pulled directly from the game client.

**Comment by catrenelle** [comment]
This should now be completed with the most recent push. A lot of text will still be in English in the UI, and will take a longer on-going effort to translate into the different languages.

If you encounter any problems, please open an issue or bring it up in the Project BR discord under the #cats-ocean-trip channel.
